version: "3"

services:
  broker:
    container_name: mqttBroker
    restart: unless-stopped
    build: ./broker
    volumes:
      - "./broker:/usr/src/broker"
      - /usr/src/broker/node_modules
    networks:
      - smart-garden-net
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
  haproxy:
    container_name: haproxy
    image: mminks/haproxy-docker-logging:latest
    ports:
      - "1883:1883"
      - "8883:8883"
      - "80:80"
      - "443:443"
    depends_on:
      - mobileApp
      - broker
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - "web-root:/var/www/next"
    networks:
      - smart-garden-net
  mobileApp:
    container_name: mobileApp
    build: ./mobileApp
    restart: unless-stopped
    volumes:
      - "web-root:/usr/src/mobileApp/packages/server/public"
    networks:
      - smart-garden-net
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/${CERTBOT_WEBROOT}
    depends_on:
      - mobileApp
    entrypoint:
      "/bin/sh -c 'certbot certonly --webroot --webroot-path=/${CERTBOT_WEBROOT} --email ${CERT_MAIL} --agree-tos --no-eff-email --force-renewal \
      -d smartgarden.timweise.com  -d www.smartgarden.timweise.com -d broker.smartgarden.timweise.com \
      && cat /etc/letsencrypt/live/smartgarden.timweise.com/fullchain.pem /etc/letsencrypt/live/smartgarden.timweise.com/privkey.pem > /etc/letsencrypt/live/smartgarden.timweise.com/smartgarden.timweise.com.pem'"

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  smart-garden-net:
