version: '3'

services:
  broker:
    container_name: mqttBroker
    # restart: always
    build: ./broker
    volumes:
      - './broker:/usr/src/broker'
      - /usr/src/broker/node_modules
    networks: 
      - smart-garden-net
    environment:
      MONGO_URI: 'mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}?authSource=admin'
  haproxy:
    container_name: haproxy
    image: mminks/haproxy-docker-logging:latest
    ports:
      - '1883:1883'
      - '8883:8883'
      - '80:80'
    volumes:
      - './haproxy:/usr/local/etc/haproxy'
      - './certs:/certs'
    networks:
      - smart-garden-net
  dashboard:
    container_name: dashboard
    build: ./dashboard
    volumes:
      - './dashboard:/usr/src/app'
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - smart-garden-net

networks: 
  smart-garden-net: