version: "3"

services:
  broker:
    container_name: mqttBroker
    build: ./broker
    volumes:
      - "./broker:/usr/src/broker"
      - /usr/src/broker/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
    networks:
      - smart-garden-net
  haproxy:
    container_name: haproxy
    image: mminks/haproxy-docker-logging:latest
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8080:80"
      - "443:443"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
      - "./certs:/etc/letsencrypt/live/smartgarden.timweise.com"
    networks:
      - smart-garden-net
    depends_on:
      - mobileapp
      - broker
  mobileapp:
    container_name: mobileapp
    build: ./mobileApp
    volumes:
      - "web-root:/usr/src/mobileApp/packages/server/public"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MQTT_HOST=${MQTT_HOST}
    networks:
      - smart-garden-net

volumes:
  web-root:

networks:
  smart-garden-net:
