apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: smart-garden
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:4.2.8
          name: mongo-database
          envFrom:
            - secretRef:
                name: dev-secret
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim