# Internal ClusterIP type Service to access the db from within the cluster
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: smart-garden
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017